### ISSUE TITLE
Breaking the rules.

### ISSUE THREAD

**Issue by hubenk** [PetarBoshnakov/dice-game#5]
Accordint to game's rules: `"Raising the bid means that the player may bid a higher quantity of the same face, or any particular quantity of a higher face. If the current player challenges the previous bid, all dice are revealed."`.
And I have never seen bot's dice revealed.

![were_are_dice](https://user-images.githubusercontent.com/92019100/212775219-78dd1d0c-0436-4597-be68-005bff769d20.png)

**Comment by PetarBoshnakov** [comment]
fixed, forgot to update here
